# Generated by Django 4.0.1 on 2022-01-19 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.CharField(max_length=200, verbose_name='Слот времени')),
            ],
            options={
                'verbose_name': 'Слот времени',
                'verbose_name_plural': 'Слоты времени',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(verbose_name='ID ученика в телеграмме')),
                ('name', models.CharField(max_length=200, verbose_name='Имя ученика')),
                ('level', models.CharField(max_length=200, verbose_name='Уровень ученика')),
                ('best_time_slots', models.ManyToManyField(related_name='best_time_students', to='dpa_app.TimeSlot', verbose_name='Наиболее подходящие слоты')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='dpa_app.group', verbose_name='Группа')),
                ('ok_time_slots', models.ManyToManyField(related_name='ok_time_students', to='dpa_app.TimeSlot', verbose_name='Допустимые слоты')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='PM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(verbose_name='ID ПМ в телеграмме')),
                ('name', models.CharField(max_length=200, verbose_name='Имя ПМ')),
                ('time_slots', models.ManyToManyField(max_length=200, related_name='pms', to='dpa_app.TimeSlot', verbose_name='Временной слот')),
            ],
            options={
                'verbose_name': 'ПМ',
                'verbose_name_plural': 'ПМы',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='dpa_app.pm', verbose_name='ПМ группы'),
        ),
        migrations.AddField(
            model_name='group',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='dpa_app.timeslot', verbose_name='Время группы'),
        ),
    ]
