# Generated by Django 4.0.1 on 2022-01-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группу', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='pm',
            options={'verbose_name': 'ПМа', 'verbose_name_plural': 'ПМов'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Ученика', 'verbose_name_plural': 'Учеников'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'Временной слот', 'verbose_name_plural': 'Временные слоты'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='f_name',
        ),
        migrations.AddField(
            model_name='student',
            name='l_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фамилия ученика'),
        ),
        migrations.AlterField(
            model_name='student',
            name='best_time_slots',
            field=models.ManyToManyField(blank=True, related_name='best_time_students', to='dpa_app.TimeSlot', verbose_name='Наиболее подходящие слоты'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ok_time_slots',
            field=models.ManyToManyField(blank=True, related_name='ok_time_students', to='dpa_app.TimeSlot', verbose_name='Допустимые слоты'),
        ),
    ]
