# Generated by Django 4.0.1 on 2022-01-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpa_app', '0003_alter_pm_options_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='link_sent',
            field=models.BooleanField(default=False),
        ),
    ]
