# Generated by Django 4.0.1 on 2022-01-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpa_app', '0004_student_link_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название рассылки')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Рассылать не ранее')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Рассылать не позднее')),
            ],
            options={
                'verbose_name': 'Дату рассылки',
                'verbose_name_plural': 'Даты рассылок',
            },
        ),
    ]
